[package]
name = "rust_rocket_example"
version = "0.1.0"
authors = ["iyeongjun <they6687@naver.com>"]

[dependencies]
rocket = "0.3.11"
rocket_codegen = "0.3.11"
diesel = { version = "<= 1.2", features = ["mysql", "r2d2"] }